### ISSUE TITLE
US-01: (Backend) Como usuario no registrado, quiero poder registrarme, para acceder a las funcionalidades de la aplicaci+on#2

### ISSUE THREAD

**Issue by bryanstgarcia** [bryanstgarcia/repo-proyecto-final#4]
Criterio de aceptación:

- [x] El endpoint la data esperada
- [x] El endpoint verifica que se está recibiendo los campos correctos
- [x] Se crea un modelo para el usuario
- [x] La contraseña del usuario se guarda de forma segura

El modelo debe contener 
Nombre
hasehd password
salt
role

```
REQUEST POST 
Application/JSON
{
 "name":  str,
 "email": str,
 "password": str
}

REPSONSE 
201
Creado satisfactoriamente

{
 "message": "Se creo de forma satisfactoria"
}

400
{
 "messasge: "No se pudo crear el usuario
}
```

**Comment by bryanstgarcia** [comment]
@Jdvd01  Cambié la estructura del enpoint a una nueva

**Comment by Jdvd01** [comment]
Para que el texto se vea como codigo tiene que ser entre 3 ``` de cada lado :D

**Comment by Jdvd01** [comment]
```
"prueba": "hola"
```
